feat(button): refactor button API#62
SNCFdevelopers/wcs pull request #75
Opened 2019-09-11 14:14 UTC by Nexyll

2019-09-11 14:40 UTC, MonsieurMan requested changes

2019-09-11 14:40 UTC, MonsieurMan commented on src/components.d.ts
> +    * Specify the shape of the button. Setting this attribute will change the height and padding of a button.
J'enlèverai le bout sur height et padding, c'est pas forcément vrai.

2019-09-11 14:40 UTC, MonsieurMan commented on src/components/button/button.tsx
> +                'wcs-inner-button-rounded': this.shape === 'round',
Je pensais l'avoir déjà enlevé, mais cette méthode ne sert à rien, on peut refaire le même comportement avec les sélecteurs ```:host()```

2019-09-11 14:40 UTC, MonsieurMan commented on src/components/button/button.tsx
> +    @Prop({ reflect: true }) icon: boolean = false;
Ont peut le supprimer aussi, le mode icon-only originellement c'est simplement le bouton 'square' qui est déjà dans le ButtonShape.

2019-09-11 14:40 UTC, MonsieurMan commented on src/components/button/button-interface.ts
>  export type ButtonType = 'button' | 'submit';
On peut en profiter pour préfixer cette affaire là

2019-09-11 15:10 UTC, Nexyll commented on src/components/button/button.tsx
> +    @Prop({ reflect: true }) icon: boolean = false;
Pour le moment si je le supprime le style des bouton avec icon changent (l'icone n'est plus centrée).

2019-09-11 15:15 UTC, Nexyll commented on src/components/button/button.tsx
> +                'wcs-inner-button-rounded': this.shape === 'round',
à faire plutôt dans un autre branche, ça n'aura pas de conséquence sur l'API du bouton.

2019-09-13 07:49 UTC, MonsieurMan requested changes
Hormis que je pense qu'il faille enlever le prefix de `wcs-button` et `wcs-submit`, ces deux noms là n'ont aucune chance de collision et ça ne fait pas gagner en lisibilité.
Et il faut rester cohérent, on aurait mit wcs-square et wcs-round aussi sinon, mais je ne suis pas pour tout préfixer.

2019-09-13 07:49 UTC, MonsieurMan commented on src/components/button/button.e2e.ts
> +                <wcs-button class="wcs-primary" type="wcs-submit"></wcs-button>
Oh, ça je l'aurais pas préfixé pour le coup. Si ?

2019-09-13 07:58 UTC, Nexyll commented on src/components/button/button.e2e.ts
> +                <wcs-button class="wcs-primary" type="wcs-submit"></wcs-button>
Nan ça me semble plus propre sans aussi, erreur de compréhension dans le première review 🙄

2019-09-13 08:17 UTC, MonsieurMan approved these changes

2019-09-13 08:31 UTC, merged