Add nav component
SNCFdevelopers/wcs pull request #83
Opened 2019-10-09 07:52 UTC by alexisponcet

2019-10-10 12:42 UTC, Nexyll requested changes

2019-10-10 12:42 UTC, Nexyll commented on src/components/nav/nav.tsx
> +                    </wcs-nav-item>
Rendre cette partie configurable par l'utilisateur

2019-10-10 12:42 UTC, Nexyll commented on src/components/nav/readme.md
> +    <wcs-nav-item text="Support" id="wcs-nav-bottom" class="d-none d-lg-block"><i class="material-icons icons icons-size-1x5">chat</i></wcs-nav-item>
Plutôt utiliser un attribut (qui du coup sera automatiquement documenté) :

Exemple d'API
```html    
<wcs-nav-item text="Support" position="bottom" class="d-none d-lg-block">
    <i class="material-icons icons icons-size-1x5">chat</i>
</wcs-nav-item>
```

Avec un attribut position pas défaut à `top`. Dans le cas d'une valeur bottom, le composant se rajoute le slot `bottom` qui va permettre au parent de le gérer dans un slot `bottom`.

L'avantage d'utiliser une propriété est de limiter les valeurs possibles avec un type et de ne pas utiliser les slots qui ne sont souvent pas maîtrisés par les développeurs Angular.

2019-10-22 08:54 UTC, MonsieurMan commented
Closed via #87

2019-10-22 08:54 UTC, closed without merging